#!/usr/bin/env bash

yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus on
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow on
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config window_border off
yabai -m config window_border_width 6
yabai -m config active_window_border_color 0xff775759
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap
yabai -m config layout bsp
yabai -m config top_padding 05
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 06

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'
yabai -m config external_bar all:28:0 # If not using a status bar like sketchybar/ubersicht


# yabai -m space --create
# yabai -m space --create
# yabai -m space --create
# yabai -m space --create

## focus previous window when window destroyed
yabai -m signal --add event=window_destroyed action="yabai -m window --focus mouse"
